# Generated by Django 6.0 on 2026-04-14 19:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_saas_auth', '0001_initial'),
        ('app_saas_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto en USD')),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Tasa de Cambio (BCV)')),
                ('amount_ves', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto en Bolívares')),
                ('method', models.CharField(choices=[('pago_movil', 'Pago Móvil'), ('zelle', 'Zelle'), ('binance', 'Binance Pay'), ('cash', 'Efectivo'), ('transfer', 'Transferencia')], default='pago_movil', max_length=20)),
                ('reference', models.CharField(help_text='ID de transacción / Referencia', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Verificación Pendiente'), ('completed', 'Cargado con Éxito'), ('failed', 'Rechazado'), ('voided', 'Anulado')], default='completed', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Notas de Auditoría')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deactivated', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='app_saas_core.productlicense')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app_saas_auth.organization')),
                ('source_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_saas_core.saasproduct')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cobro / Pago',
                'verbose_name_plural': 'Cobros / Pagos',
                'ordering': ['-created_at'],
            },
        ),
    ]
