# Generated by Django 6.0.4 on 2026-04-20 02:32

import app_saas_core.gateway_models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_saas_core', '0003_alter_productlicense_organization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAPIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Ej: 'Producción Railway', 'Dev Local'", max_length=100, verbose_name='Alias de la clave')),
                ('key', models.CharField(default=app_saas_core.gateway_models.generate_service_key, editable=False, max_length=128, unique=True, verbose_name='Clave API')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Activa?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Actualizamos esto con cada llamada exitosa al Gateway.', null=True, verbose_name='Último uso')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revocación')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='app_saas_core.saasproduct', verbose_name='Producto Satélite')),
            ],
            options={
                'verbose_name': 'API Key de Servicio',
                'verbose_name_plural': 'API Keys de Servicios',
                'ordering': ['-created_at'],
            },
        ),
    ]
