# Generated by Django 6.0.4 on 2026-04-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_saas_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='clarapos_tenant_id',
            field=models.UUIDField(blank=True, help_text='UUID del tenant_id asociado en la base de datos de ClaraPOS', null=True, verbose_name='Tenant ID en ClaraPOS'),
        ),
    ]
